### ISSUE TITLE
Make Package available

### ISSUE THREAD

**Issue by moe2k** [b13/menus#1]
Can it be that the package b13/menus is not yet available, neither on packagist nor in TER?

`composer req b13/menus`
                                                                                                                                                                  
 ```
 [InvalidArgumentException]                                                                                                                                      
  Could not find a matching version of package b13/menus. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).  
```
Adding stability constraint @dev does not help.

**Comment by bmack** [comment]
That is correct. We're currently fixing the last issues, and hopefully we can release a stable version within the next few days (also on packagist and TER).

**Comment by bmack** [comment]
It's now available on packagist https://packagist.org/packages/b13/menus - and available in TER once we have a tagged version of course.

**Comment by moe2k** [comment]
Great, thanks a lot!
