### ISSUE TITLE
LanguageMenu does not create links for plugins

### ISSUE THREAD

**Issue by rintisch** [b13/menus#106]
*Problem*
The `TYPO3\CMS\Frontend\DataProcessing\LanguageMenuProcessor` creates links on pages with plugins (means: which have query parameters).
The `B13\Menus\DataProcessing\LanguageMenu` does not create links for these pages. 

Or am I missing something?

**Comment by achimfritz** [comment]
i think you use f:link.typolink or f:link.page, for creating Links for languageMenu, so you can use
addQueryString addQueryStringExclude/argumentsToBeExcludedFromQueryString arguments (see description in VH)
