### ISSUE TITLE
BreadcrumbsMenu: excludeDoktypes ignored

### ISSUE THREAD

**Issue by bippesbrandao** [b13/menus#11]
Hi all,

for the Breadcrumbs Menu the excludeDoktypes config is ignored.
Could be something like this in BreadcrumbsMenu:porcess:

`        if (!empty($processorConfiguration['excludeDoktypes'])) {
            $excludedDoktypes = GeneralUtility::intExplode(',', $processorConfiguration['excludeDoktypes']);
            foreach ($GLOBALS['TSFE']->rootLine as $page) {
                if (array_search($page['doktype'], $excludedDoktypes) === false ) {
                    $rootline[] = $page;
                }
            }
        } else {
            $rootline = $GLOBALS['TSFE']->rootLine;
        }

        $pages = $this->menuRepository->getBreadcrumbsMenu($rootline);
`
best regards
Arne

**Comment by achimfritz** [comment]
https://github.com/b13/menus/pull/16/commits/99a440dded8c423eb88653ebec4894f4c91deec9 will fix this
