### ISSUE TITLE
TreeMenu does not list pages created in a workspace

### ISSUE THREAD

**Issue by infabo** [b13/menus#25]
Yeah, basically as the topic already says: TreeMenu does not list pages which where created in an active workspace.

Although TreeMenu lists Workspace-Versions for changed-in-workspace pages, it simply ignores new pages.

**Comment by achimfritz** [comment]
Workspaces are not considered in Menu-Caching at all, we should disable Caching for Workspace.

**Comment by infabo** [comment]
I reported the issue before Menu caching was introduced. And Cache clearing did Not resolve the issue Back then. Are you Sure this works now? I havent checked yet.

**Comment by achimfritz** [comment]
i have not test new pages (only edited), maybe you are right, i will test it (but Menu-Caching was introduced from beginning)

**Comment by infabo** [comment]
I guess it is not so trivial for new pages.

**Comment by achimfritz** [comment]
works for me also with new pages, would you test and verify this?
