### ISSUE TITLE
Exclude doktypes from rendering

### ISSUE THREAD

**Issue by georgringer** [b13/menus#29]
It would be great to have the possibility to define doktypes which shouldn't be rendered. Best examples are spacer pages

**Comment by sbuerk** [comment]
From the readme on https://github.com/b13/menus#common-options-for-all-menus:

> Common Options for all menus
> excludePages - a list of page IDs (and their subpages if Tree Menu is used) to exclude from the page
> excludeDoktypes - a list of doktypes that are not rendered. BE_USER_SECTIONs are excluded by default. SYS_FOLDERs are queried (for subpages etc) but never rendered.

That is more on not retrieving. But anyway, if retrieved you can ignore it in the fluid template based on the doktype (or using a condition in typoscript).

Anyway there are a special flag for the spacers:

> In TypoScript this is available as field:isSpacer, in Fluid, this is accessible in {page.isSpacer}

**Comment by georgringer** [comment]
thx, yes but if it wouldn't be in the result set it would also be nice, also for stuff like counting sub pages

**Comment by achimfritz** [comment]
Hi @georgringer , doesn't that  work?: `excludeDoktypes = 199,200,100,205` (or do i missunderstand this issue?)

**Comment by achimfritz** [comment]
closed due no feedback
