### ISSUE TITLE
BreadcrumbsMenu does not consider pages.nav_hide

### ISSUE THREAD

**Issue by AMartinNo1** [b13/menus#30]
I noticed that `pages.nav_hide` is currently not considered by `BreadcrumbsMenu`. Is that on purpose? We've the situation that we would like to remove a page and said field has no effect in frontend.

TYPO3: v9.5.20
menus: [dev-master#e1b0c5aeadaf37b20a6ebe9fb9779f9efcc91b71](https://github.com/b13/menus/commit/e1b0c5aeadaf37b20a6ebe9fb9779f9efcc91b71)

**Comment by achimfritz** [comment]
not only in BreadcrumbMenu, all Menus (excluding submenu pages of tree-menu in default language) do not consider `nav_hide`
