### ISSUE TITLE
Anonymous function in TreeMenuCompiler: $contentObjectRenderer is in "use" but not accessed

### ISSUE THREAD

**Issue by nostadt** [b13/menus#37]
https://github.com/b13/menus/blob/58bd79833c5555f0b17ae9b492b0f831db494b3a/Classes/Compiler/TreeMenuCompiler.php#L34

I've noticed that the variable `$contentObjectRenderer` is passed to the anonymous function in `use` but not accessed within it.

Am I missing something or can it be dropped safely?

**Comment by AMartinNo1** [comment]
I wanted to remove this but couldn't find a contributing guide.

`./Build/Scripts/runTests.sh` leads to pulling various docker images on my mac and but also this error:

```
Status: Downloaded newer image for typo3gmbh/php72:latest
Creating local_unit_run ... error

ERROR: for local_unit_run  Cannot create container for service unit: invalid volume specification: '.:.:rw': invalid mount config for type "volume": invalid mount path: '.' mount path must be absolute

ERROR: for unit  Cannot create container for service unit: invalid volume specification: '.:.:rw': invalid mount config for type "volume": invalid mount path: '.' mount path must be absolute
ERROR: Encountered errors while bringing up the project.
Removing network local_default
```
