### ISSUE TITLE
Bug: LanguageMenu excludes "nav_hide" pages

### ISSUE THREAD

**Issue by infabo** [b13/menus#38]
LanguageMenu should not exclude "nav_hide" pages as this is against the use-case. It makes so sense to adhere this page-attribute in a language-menu context.

see https://github.com/b13/menus/blob/58bd79833c5555f0b17ae9b492b0f831db494b3a/Classes/Compiler/LanguageMenuCompiler.php#L47

and escpecially https://github.com/b13/menus/blob/58bd79833c5555f0b17ae9b492b0f831db494b3a/Classes/Domain/Repository/MenuRepository.php#L81

**Comment by josefglatz** [comment]
@bmack What do you think? I can create a PR

**Comment by bmack** [comment]
@josefglatz yes please.

**Comment by achimfritz** [comment]
is this not already fixed with https://github.com/b13/menus/commit/a746bf269e41719f024a475d81a4617b1b81969b ?

**Comment by josefglatz** [comment]
> is this not already fixed with https://github.com/b13/menus/commit/a746bf269e41719f024a475d81a4617b1b81969b ?

Ah have to check first! Thank you

**Comment by bmack** [comment]
Looks like this is solved
