### ISSUE TITLE
v10 compatibility missing in composer.json of 0.2.0

### ISSUE THREAD

**Issue by rintisch** [b13/menus#40]
It's not possible to install a tagget version of this extension on TYPO3 v10 via composer because in the [composer.json](https://github.com/b13/menus/blob/v0.2.0/composer.json#L6-L10) of the latest version the compatibility is limited to v.9.5:

```json
  "require": {
    "php": "^7.2",
    "typo3/cms-core": "^9.5",
    "typo3/cms-frontend": "^9.5"
  },
```

I saw that v10 compatibility was added in master branch 10months ago. Would be nice to have v10 compatibilty in a tagged version.  Or are there any unsolved problems with v10?

**Comment by bmack** [comment]
We tagged EXT:menus 0.2.1 yesterday. Thanks for the information.
