### ISSUE TITLE
Pre-resolve menu item urls

### ISSUE THREAD

**Issue by christophlehmann** [b13/menus#45]
Currently menu items does not contain the their url.

When i use the f:link.page or f:link.typolink ViewHelper a lot of code is executed to resolve an url for a menu item by `{item.uid}` which also means extra SQL queries for every menu item. So my idea is to resolve the urls before they go to cache.

What do you think?

With that one can simple write `<a href={item.url}>{item.nav_title}</a>`

**Comment by bmack** [comment]
Hi @christophlehmann ,

the main problem with this approach are the followings:
* using `<f:link.typolink>` handles e.g. target attribute / additional params / JS window params / additional classes 1:1 as Core does (which I think is a good thing). Using `{item.url}`would mean that the typical "Typolink" (see TypoLinkCodecService in Core) would be much harder to support. Maybe a custom viewHelper could help, actually. `<menu:link>{item}</menu:link>`.
* if we "cache" the URLs, this would definitively be faster, but we would loose logic like "link to access restricted pages" or specific `config.typolink_additionalParams` settings which are depending not just per page, but per TypoScript condition per page (also e.g. per user-group).

Maybe a second cache entry (with the generated links) would solve this...

**Comment by christophlehmann** [comment]
Hi @bmack Thanks for your clarification. If it's not something which can be solved in this ext we can close it ;-)
