### ISSUE TITLE
Bug: TreeMenu and translated hidden pages

### ISSUE THREAD

**Issue by infabo** [b13/menus#46]
When you translate a page and hide the translation, you still get the default-page-variant in the output.

Scenario with DE and EN site language and 2 pages:

- Seite A
- Seite B

Translate pages:

- Seite A -> Page A
- Seite B -> Page B

Now: 

- disable/hide `Page B`

Expected treemenu when visiting `EN website`:

- Page A

Actual result:

- Page A
- Seite B

**Comment by infabo** [comment]
Hum, nevermind. This bug haunts me. https://forge.typo3.org/issues/90233

But ain't Bill Murray...

**Comment by achimfritz** [comment]
i think this is a core issue, not an EXT:menu
