### ISSUE TITLE
Flush alle caches by tags

### ISSUE THREAD

**Issue by lochmueller** [b13/menus#59]
Hey @bmack 

Thanks for the fix in https://github.com/b13/menus/issues/47 Do you saw my info related to the cache invalidation? Why you only drop two caches: https://github.com/b13/menus/blob/master/Classes/Hooks/DataHandlerHook.php#L64 (hash and pages) It is impossible for EXT:staticfilecache to get the "clear cache" in its own cache. The StaticFileCache entry is also tagged with menuId_XXX. Why don't you use flushCachesByTags() to support all caches that are tagged with the menuId_XXX tags?
https://api.typo3.org/master/class_t_y_p_o3_1_1_c_m_s_1_1_core_1_1_cache_1_1_cache_manager.html#ae8af86d7af4c26e4d6aae11ab07585fd
Nice side effect: The implementation would be smaller :)

Thank you for your feedback.
If I have a mistake in my thoughts, just close the ticket. 

Regards,
Tim

**Comment by bmack** [comment]
Hey Tim,

thanks for the feedback. I did _not_ read your input there. I'm sorry.

So, you mean, we should just use `flushCachesInGroupByTags()` ?

If you're up for a PR, I'm happy to review.

**Comment by lochmueller** [comment]
Done. PR is pushed to your repo.
