### ISSUE TITLE
cacheHelper must respect preview visibility

### ISSUE THREAD

**Issue by bommelpeter** [b13/menus#61]
The visibility aspect must be taken into account to prevent (A) delivering hidden pages from cache or (B) enable admPanel preview of hidden pages (`showHiddenPages`).

Until then, b13/menus is (at least) broken/incompatible with Admin Panel's "showHiddenPages" feature: 
If visiting a site with showHiddenPages=1, either 
(A) **_b13/menus may deliver hidden pages without backend login_** (if b13/menus' data not yet cached) or 
(B) "showHiddenPages" isn't respected (if b13/menus' data already cached) 

Possible solutions: 
- own cache entries depending on visibility aspect (may be done in `AbstractMenuCompiler::generateCacheIdentifierForMenu`) 
-  not caching b13/menus at all if (pseudo-code) `TYPO3\CMS\Core\Context\Context::getAspect('visibility')->get('includeHiddenPages')` returns true.

**Comment by bmack** [comment]
Fixed with https://github.com/b13/menus/commit/052c3aa6d8f3727cb047565c9cf50fbd3e4c42f9
