### ISSUE TITLE
Hidden pages without link in cache

### ISSUE THREAD

**Issue by pnoreck** [b13/menus#65]
We have the problem that our customer uses in TYPO3 11.5 the preview feature to get a preview of his hidden pages. The TreeMenu generates for the preview the menu with hidden pages and everything looks fine.

[Page 1] [Page 2] [Page 3] [Page 4 (hidden)]

But at the same time it also generates the cache for the regular user and adds the hidden pages to the menu too but without links. 

[Page 1] [Page 2] [Page 3] Page 4 (hidden)

(The missing brackets should represent the missing link) ;o)

This is easily reproducible with the admin panel -> show hidden pages.

**Comment by steffenf14** [comment]
We experience the same problem. Clearing cache helps but after a while they reappear.

**Comment by bmack** [comment]
Solution is to also include the Visibility Aspect flags into the cache.
