### ISSUE TITLE
usergroup of current frontend user is not being respected

### ISSUE THREAD

**Issue by iammati** [b13/menus#72]
I've noticed that the call here https://github.com/b13/menus/blob/master/Classes/Domain/Repository/MenuRepository.php#L156-L162 to get the generated menu as array is not generating a proper SQL expression for the current logged-in frontend user.

I'd have to implement this:
```php
$usergroup = $GLOBALS['TSFE']->fe_user->user['usergroup'];

$this->pageRepository->where_groupAccess = <<<SQL
    AND ((`pages`.`fe_group` IN ({$usergroup}))
    OR (`pages`.`fe_group` = '')
    OR (`pages`.`fe_group` IS NULL)
    OR (`pages`.`fe_group` = '0'))
SQL;
```

since the current `$this->pageRepository->where_groupAccess` returns me the same SQL expression just as my custom one with the only difference that `AND ((`pages`.`fe_group` IN ({$usergroup}))` is NOT presence.

I'm not aware about TYPO3's core where it's actually defining the `where_groupAccess` to the `$GLOBALS` (or using `UserAspect` or whatsoever) but in my (rare, I assume) use-case I'd need such implementation since my frontend login is underlying an AJAX call via middleware. OTOH the `MenuRepository` is being called post the whole middleware stack has been iterated through.

In the current state I'd need to fork the whole extension and adjust this or perform a composer-patch but I guess it's either fundamentally missing something in the core or my own configuration is wrong...

Would appreciate any information about this! :)

**Comment by bmack** [comment]
Hey @iammati ,

what TYPO3 version are you using?

**Comment by iammati** [comment]
> Hey @iammati ,
> 
> 
> 
> what TYPO3 version are you using?

TYPO3 11.5 with PHP 8

**Comment by achimfritz** [comment]
Hi @iammati can this issue be closed? (s. frontend test that verifies correct behaviour https://github.com/b13/menus/pull/81/commits/32e5e349691da1e740741bc98dd5c0d2e00da24d). if not please give an detailed example, when this is not working

**Comment by Etmolf** [comment]
I'm currently experiencing a similar issue with TreeMenu in TYPO3 v13 and menus 1.1.3. The problem is that the TYPO3 PageRepository does not receive (or already has) the correct context, causing the logged-in frontend user to be lost.

If you create a new instance of the repository with the currently valid context shortly before calling `$this->pageRepository->getMenu()`, the `PageRepository` can correctly read the user groups and build the WHERE condition.

`B13\Menus\Domain\Repository\MenuRepository.php`
```php
public function getSubPagesOfPage(int $pageId, int $depth, array $configuration)
    {
        // [...]
        $pageTree = $this->pageRepository->getMenu(
            $pageId,
            '*',
            'sorting',
            'AND doktype NOT IN (' . implode(',', $excludedDoktypes) . ') ' . $whereClause,
            false
        );
        
        // $pageTree is missing pages with user and/or group access restrictions
        
        // create new instance of PageRepository with current (valid) context
        $this->pageRepository = GeneralUtility::makeInstance(PageRepository::class, $this->context);

        $pageTree = $this->pageRepository->getMenu([...]);
        
        // $pageTree now also contains all the previously missing pages
    }
```

Since both `Context` and `PageRepository` are injected in the constructor of MenuRepository.php, I'm not sure why this is a problem. I'll probably have to dig a little deeper.
