### ISSUE TITLE
Typo3 V12 Support - GeneralUtility::intExplode second parameter must be a string

### ISSUE THREAD

**Issue by RTPAst** [b13/menus#88]
GeneralUtility::intExplode second parameter must be a string in this files:

Classes/Compiler/ListMenuCompiler.php
Classes/Compiler/TreeMenuCompiler.php

**Comment by bmack** [comment]
Care to create a pull request? would be great.

**Comment by RTPAst** [comment]
Pull requests are created

**Comment by schrej-zz** [comment]
I think, this issue can be close as PR is merged.
