### ISSUE TITLE
option to omit current language from languageMenu

### ISSUE THREAD

**Issue by masi** [b13/menus#92]
A setup for a two-language site does not need to configure `excludeLanguages` with TS conditions per language or check for `isActiveLanguage` in a Fluid-loop, if this option is avaliable.

Either `excludeCurrentLanguage = 1` or `excludeLanguages = _current,foo,bar 
`

**Comment by chesio** [comment]
Hi @masi,

`excludeLanguages` setting allows use of `stdWrap`, so if you only want to exclude current language, you can do following (I just tested it with TYPO3 12):

```
menu = B13\Menus\DataProcessing\LanguageMenu
menu {
    [...]

    excludeLanguages.data = context:language:id
}
```

**Comment by achimfritz** [comment]
@masi i think this can be closed?
